### ISSUE TITLE
PCG64 import error

### ISSUE THREAD

**Issue by GergelyTuri** [ACCLAB/DABEST-python#101]
Hi, 
I'm working on the tutorial and I get the following error when I try to do `two_groups_unpaired.mean_diff` : 
```
from numpy.random import PCG64, RandomState
# rng = RandomState(default_rng(random_seed))

ImportError: cannot import name 'PCG64'
```
I'm on Windows 10, using the python version (0.3.0), numpy = 1.15.1, pandas=0.25.3

best,

**Comment by josesho** [comment]
Hi,

Sorry about this! The minimal version of numpy should be 1.17, not 1.15. I will update `setup.py` to fix this; in the meantime, you should run 

```shell
pip install --upgrade numpy
```

or 

```shell
conda install -c conda-forge numpy>=1.17
```

Let me know if this fixes it!

Joses

**Comment by mooreniemi** [comment]
I experienced this issue as well and found upgrading to 1.18 fixed it.

**Comment by GergelyTuri** [comment]
Thanks, it was the numpy version indeed.  It works fine with `numpy==1.18.4`.
