### ISSUE TITLE
pip install dabest producing error

### ISSUE THREAD

**Issue by jjessicahorton** [ACCLAB/DABEST-python#198]
Hi there!

I'm running Windows 11 on the Surface Pro 11 (ARM chip), and using Python 3.12.4. In my terminal, I tried to execute the command `pip install dabest` and was met with this error:

```
(base) C:\Users\jjess>pip install dabest
Collecting dabest
  Using cached dabest-2024.3.29-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: fastcore in c:\users\jjess\miniconda3\lib\site-packages (from dabest) (1.7.28)
Collecting pandas~=1.5.0 (from dabest)
  Using cached pandas-1.5.3.tar.gz (5.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy~=1.23.5 (from dabest)
  Using cached numpy-1.23.5.tar.gz (10.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\jjess\miniconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\jjess\miniconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\jjess\miniconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\jjess\miniconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\jjess\miniconda3\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\jjess\AppData\Local\Temp\pip-build-env-rknoi4yj\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\jjess\AppData\Local\Temp\pip-build-env-rknoi4yj\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\jjess\AppData\Local\Temp\pip-build-env-rknoi4yj\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I looked up the attribute error, and a post on [StackOverflow](https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean) suggested trying this by running the following prompts:

`python -m ensurepip --upgrade`
`python -m pip install --upgrade setuptools`
`python -m pip install dabest`

which then gave me this:

```
Collecting dabest
  Using cached dabest-2024.3.29-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: fastcore in c:\users\jjess\miniconda3\lib\site-packages (from dabest) (1.7.28)
Collecting pandas~=1.5.0 (from dabest)
  Using cached pandas-1.5.3.tar.gz (5.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy~=1.23.5 (from dabest)
  Using cached numpy-1.23.5.tar.gz (10.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\jjess\miniconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\jjess\miniconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\jjess\miniconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\jjess\miniconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\jjess\miniconda3\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\jjess\AppData\Local\Temp\pip-build-env-q_rn3j_h\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\jjess\AppData\Local\Temp\pip-build-env-q_rn3j_h\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\jjess\AppData\Local\Temp\pip-build-env-q_rn3j_h\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

A discussion on [GitHub](https://github.com/pypa/pip/issues/12179) suggested this could possibly be an issue with the package that needs to be reported, so in case this is true I thought I'd reach out and share. If this is not an issue with the package, can you help me install `dabest` ? I have also tried cloning the repository to no avail. Thank you so much!

**Comment by JAnns98** [comment]
Hi @jjessicahorton, thanks for bringing this up. 

The current version of dabest does not work with Python 3.12 due to certain outdated modules (e.g., NumPy). The dev branch has been updated to work on Python 3.12 - this will be released in the upcoming month or so! 

In the meantime, you could either create an environment with an older version of Python (e.g., 3.9), or you could try out the dev branch:
`pip install git+https://github.com/ACCLAB/DABEST-python@vnbdev`

**Comment by jjessicahorton** [comment]
Hi there,

Thank you so much for getting back to me!! This solution worked very well for me and I really appreciate your time. Take care!

**Comment by jjessicahorton** [comment]
Hello again!

I am trying to create a new environment on my computer wherein I'm opting to use `dabest` again, and I tried to use the prompt you provided me with up above but I ran into this error:

```
pip install git+https://github.com/ACCLAB/DABEST-python@vnbdev
Collecting git+https://github.com/ACCLAB/DABEST-python@vnbdev
  Cloning https://github.com/ACCLAB/DABEST-python (to revision vnbdev) to c:\users\jjess\appdata\local\temp\pip-req-build-c497uzk3
  Running command git clone --filter=blob:none --quiet https://github.com/ACCLAB/DABEST-python 'C:\Users\jjess\AppData\Local\Temp\pip-req-build-c497uzk3'
  Running command git checkout -b vnbdev --track origin/vnbdev
  branch 'vnbdev' set up to track 'origin/vnbdev'.
  Switched to a new branch 'vnbdev'
  Resolved https://github.com/ACCLAB/DABEST-python to commit 1d8c5e1305d5ceeb48e4b8d6730316abf5bad89b
  Preparing metadata (setup.py) ... done
Collecting fastcore (from dabest==2024.3.30)
  Using cached fastcore-1.7.29-py3-none-any.whl.metadata (3.6 kB)
Collecting pandas~=2.1.4 (from dabest==2024.3.30)
  Downloading pandas-2.1.4.tar.gz (4.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 14.1 MB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [58 lines of output]
      Ignoring oldest-supported-numpy: markers 'python_version < "3.12"' don't match your environment
      Collecting meson-python==0.13.1
        Downloading meson_python-0.13.1-py3-none-any.whl.metadata (4.1 kB)
      Collecting meson==1.2.1
        Downloading meson-1.2.1-py3-none-any.whl.metadata (1.7 kB)
      Collecting wheel
        Using cached wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
      Collecting Cython<3,>=0.29.33
        Using cached Cython-0.29.37-py2.py3-none-any.whl.metadata (3.1 kB)
      Collecting numpy<2,>=1.26.0
        Downloading numpy-1.26.4.tar.gz (15.8 MB)
           -------------------------------------- 15.8/15.8 MB 863.8 kB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        Preparing metadata (pyproject.toml) did not run successfully.
        exit code: 1

        [21 lines of output]
        + C:\Users\jjess\Documents\MEGA\Bellemer_Lab\sara_data\env\python.exe C:\Users\jjess\AppData\Local\Temp\pip-install-pb8umcos\numpy_bdc44827bd944f49bd4fd19900c9540d\vendored-meson\meson\meson.py setup C:\Users\jjess\AppData\Local\Temp\pip-install-pb8umcos\numpy_bdc44827bd944f49bd4fd19900c9540d C:\Users\jjess\AppData\Local\Temp\pip-install-pb8umcos\numpy_bdc44827bd944f49bd4fd19900c9540d\.mesonpy-qkdphiaj -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\jjess\AppData\Local\Temp\pip-install-pb8umcos\numpy_bdc44827bd944f49bd4fd19900c9540d\.mesonpy-qkdphiaj\meson-python-native-file.ini
        The Meson build system
        Version: 1.2.99
        Source dir: C:\Users\jjess\AppData\Local\Temp\pip-install-pb8umcos\numpy_bdc44827bd944f49bd4fd19900c9540d
        Build dir: C:\Users\jjess\AppData\Local\Temp\pip-install-pb8umcos\numpy_bdc44827bd944f49bd4fd19900c9540d\.mesonpy-qkdphiaj
        Build type: native build
        Project name: NumPy
        Project version: 1.26.4
        WARNING: Failed to activate VS environment: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

        ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
        The following exception(s) were encountered:
        Running `icl ""` gave "[WinError 2] The system cannot find the file specified"
        Running `cl /?` gave "[WinError 2] The system cannot find the file specified"
        Running `cc --version` gave "[WinError 2] The system cannot find the file specified"
        Running `gcc --version` gave "[WinError 2] The system cannot find the file specified"
        Running `clang --version` gave "[WinError 2] The system cannot find the file specified"
        Running `clang-cl /?` gave "[WinError 2] The system cannot find the file specified"
        Running `pgcc --version` gave "[WinError 2] The system cannot find the file specified"

        A full log can be found at C:\Users\jjess\AppData\Local\Temp\pip-install-pb8umcos\numpy_bdc44827bd944f49bd4fd19900c9540d\.mesonpy-qkdphiaj\meson-logs\meson-log.txt
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Seems pretty similar to what I was dealing with initially. For now I've instead just opted to work on this separate project within the original environment I was able to set up a few weeks ago, but I figured it'd probably be worthwhile to share that I ran into this again. Do you have any advice as to what I should do differently? Thank you again for your time!!

**Comment by JAnns98** [comment]
Hey, just to update this, I have just merged a branch into vnbdev that updates the various dependencies required for Python 3.13 compatibility. If you are sticking to python 3.13, you can try installing the vnbdev branch again as I illustrated.
